### ISSUE TITLE
Workflow step succeeds, even if octodns-sync fails

### ISSUE THREAD

**Issue by solvaholic** [solvaholic/octodns-sync#40]
## Description

From https://github.com/solvaholic/octodns-sync/issues/35#issuecomment-765792020 :

> The first thing I noticed was if there are errors running OctoDNS a comment is still left on the pr. I don't think this is really an issue, it's just not what I expected since OctoDNS didn't successfully run. I figured this step would throw an error and the workflow would end here. My initial run had the wrong api credentials which resulted in the following log output:
> 
> ```text
> Traceback (most recent call last):
>   File "/usr/local/bin/octodns-sync", line 8, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.7/site-packages/octodns/cmds/sync.py", line 37, in main
>     manager = Manager(args.config_file)
>   File "/usr/local/lib/python3.7/site-packages/octodns/manager.py", line 118, in __init__
>     self.providers[provider_name] = _class(provider_name, **kwargs)
>   File "/usr/local/lib/python3.7/site-packages/octodns/provider/rackspace.py", line 64, in __init__
>     auth_token, dns_endpoint = self._get_auth_token(username, api_key)
>   File "/usr/local/lib/python3.7/site-packages/octodns/provider/rackspace.py", line 85, in _get_auth_token
>     x['name'] == 'cloudDNS'][0]['endpoints'][0]['publicURL']
> IndexError: list index out of range
> ```
> 
> And this is the comment that was left:
> 
> ![github com_paramax_dns_pull_2](https://user-images.githubusercontent.com/831974/105559694-d2db9380-5cdf-11eb-9653-984f2bce883a.png)

## Expected Behavior

> I figured this step would throw an error and the workflow would end here.

## Actual Behavior

> if there are errors running OctoDNS a comment is still left on the pr.

## Possible Fix

> I figured this step would throw an error and the workflow would end here.

## Steps to Reproduce

1. Enable and configure this action
1. Enable and configure `add_pr_comment`
1. Run octodns-sync with invalid credentials

## Context

> I don't think this is really an issue, it's just not what I expected since OctoDNS didn't successfully run.

## Your Environment

* Version used: main
* Link to your project:

**Comment by solvaholic** [comment]
fwiw I suspect this is similar to #23

**Comment by solvaholic** [comment]
> IndexError: list index out of range

Here's what runs `octodns-sync` now:

```bash
if [ "${_doit}" = "--doit" ]; then
  script "${_logfile}" -e -c \
  "octodns-sync --config-file=\"${_config_path}\" --doit \
  >>\"${_planfile}\""
else
  script "${_logfile}" -e -c \
  "octodns-sync --config-file=\"${_config_path}\" \
  >>\"${_planfile}\""
fi
```

`octodns-sync` returns non-zero when it fails, and `script -e` returns the correct code. `entrypoint.sh` just doesn't respond to it. I think this should be straightforward, will set up a fix to test.

**Comment by solvaholic** [comment]
Got a successful test of this (that is: the step failed) over in:

https://github.com/solvaholic/scaling-succotash/runs/1914410445?check_suite_focus=true
